import DashboardNav from "@/share/DashboardNav";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  
  return (
   <>
   <DashboardNav />
   {children}
   </>
  );
}
